In [3]:
import pandas as pd
import json

df = []

with open('ml.json') as f: 
    for line in f.readlines():
        df.append(json.loads(line))

df_eda2 = pd.DataFrame(df)

In [6]:
df_eda2

                    genres  price metascore  release_year
0                 [Action]   9.99        96          1998
1               [Strategy]   6.99        84          2006
2               [Strategy]   6.99        80          2006
3     [Action, Indie, RPG]   9.99        76          2006
4                 [Action]   9.99        70          2005
...                    ...    ...       ...           ...
2496              [Action]   4.99        71          2001
2497   [Action, Adventure]  14.99        88          2002
2498              [Action]   4.99        79          2003
2499              [Action]  14.99        93          2004
2500              [Action]   9.99        65          2004

[2501 rows x 4 columns]

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MultiLabelBinarizer


data = df_eda2

X = data[['release_year', 'genres']]
y = data['price']

#caracteristicas binarias con MultiLabelBinarizer
mlb = MultiLabelBinarizer()
genres_encoded = pd.DataFrame(mlb.fit_transform(X['genres']), columns=mlb.classes_, index=X.index)

X = pd.concat([X.drop('genres', axis=1), genres_encoded], axis=1)

#entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.21, random_state=70)

print(X_test.info())

#Random Forest
modelo_random_forest = RandomForestRegressor(n_estimators=100, random_state=100)
modelo_random_forest.fit(X_train, y_train)

#predict
y_pred = modelo_random_forest.predict(X_test)

#evaluacion
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)


print(f"RMSE: {rmse}")
print(f"R2: {r2}")

<class 'pandas.core.frame.DataFrame'>
Index: 526 entries, 442 to 272
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   release_year           526 non-null    int64
 1   Action                 526 non-null    int32
 2   Adventure              526 non-null    int32
 3   Casual                 526 non-null    int32
 4   Early Access           526 non-null    int32
 5   Free to Play           526 non-null    int32
 6   Indie                  526 non-null    int32
 7   Massively Multiplayer  526 non-null    int32
 8   RPG                    526 non-null    int32
 9   Racing                 526 non-null    int32
 10  Simulation             526 non-null    int32
 11  Sports                 526 non-null    int32
 12  Strategy               526 non-null    int32
dtypes: int32(12), int64(1)
memory usage: 32.9 KB
None
RMSE: 8.194215961503977
R2: 0.4053934917647908

In [5]:
print(genres_encoded)

      Action  Adventure  Casual  Early Access  Free to Play  Indie
0          1          0       0             0             0      0  \
1          0          0       0             0             0      0
2          0          0       0             0             0      0
3          1          0       0             0             0      1
4          1          0       0             0             0      0
...      ...        ...     ...           ...           ...    ...
2496       1          0       0             0             0      0
2497       1          1       0             0             0      0
2498       1          0       0             0             0      0
2499       1          0       0             0             0      0
2500       1          0       0             0             0      0

      Massively Multiplayer  RPG  Racing  Simulation  Sports  Strategy
0                         0    0       0           0       0         0
1                         0    0       0           0       0         1
2                         0    0       0           0       0         1
3                         0    1       0           0       0         0
4                         0    0       0           0       0         0
...                     ...  ...     ...         ...     ...       ...
2496                      0    0       0           0       0         0
2497                      0    0       0           0       0         0
2498                      0    0       0           0       0         0
2499                      0    0       0           0       0         0
2500                      0    0       0           0       0         0

[2501 rows x 12 columns]

In [10]:
import joblib

modelo_entrenado = modelo_random_forest

joblib.dump(modelo_entrenado, 'modelo_entrenado.pkl')

['modelo_entrenado.pkl']